// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { PasswordAuthApiV1AuthPasswordAuthenticatePostData, PasswordAuthApiV1AuthPasswordAuthenticatePostError, PasswordAuthApiV1AuthPasswordAuthenticatePostResponse, PasswordRegistrationApiV1AuthPasswordRegisterPostData, PasswordRegistrationApiV1AuthPasswordRegisterPostError, PasswordRegistrationApiV1AuthPasswordRegisterPostResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Password Auth
 */
export const passwordAuthApiV1AuthPasswordAuthenticatePost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PasswordAuthApiV1AuthPasswordAuthenticatePostData, ThrowOnError>) => {
    return (options?.client ?? client).post<PasswordAuthApiV1AuthPasswordAuthenticatePostResponse, PasswordAuthApiV1AuthPasswordAuthenticatePostError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/password/authenticate'
    });
};

/**
 * Password Registration
 */
export const passwordRegistrationApiV1AuthPasswordRegisterPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PasswordRegistrationApiV1AuthPasswordRegisterPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<PasswordRegistrationApiV1AuthPasswordRegisterPostResponse, PasswordRegistrationApiV1AuthPasswordRegisterPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/password/register'
    });
};