// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PasswordEmailAuthImport = {
    email: string;
    raw_password: string;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type PasswordAuthApiV1AuthPasswordAuthenticatePostData = {
    body: PasswordEmailAuthImport;
};

export type PasswordAuthApiV1AuthPasswordAuthenticatePostResponse = (Token);

export type PasswordAuthApiV1AuthPasswordAuthenticatePostError = (HTTPValidationError);

export type PasswordRegistrationApiV1AuthPasswordRegisterPostData = {
    body: PasswordEmailAuthImport;
};

export type PasswordRegistrationApiV1AuthPasswordRegisterPostResponse = (Token);

export type PasswordRegistrationApiV1AuthPasswordRegisterPostError = (HTTPValidationError);

export type TestAuthApiV1AuthPasswordTestGetResponse = (Token);

export type TestAuthApiV1AuthPasswordTestGetError = unknown;