"""change firebase_uid of users to char column

Revision ID: 3cc0aa9f08fd
Revises: bafad400c9ed
Create Date: 2024-12-30 17:15:01.815843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc0aa9f08fd'
down_revision = 'bafad400c9ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade DB.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade DB.
    """
    raise NotImplementedError("Downgrade is not supported")