"""add firebase_uuid and password to users

Revision ID: 82c26f76d78a
Revises: dd4432561444
Create Date: 2024-12-26 14:18:18.652530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c26f76d78a'
down_revision = 'dd4432561444'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade DB.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uuid', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('password', sa.CHAR(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade DB.
    """
    raise NotImplementedError("Downgrade is not supported")