"""add password_salt to users

Revision ID: baa4ee9d8adf
Revises: 3cc0aa9f08fd
Create Date: 2024-12-31 18:08:10.925109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa4ee9d8adf'
down_revision = '3cc0aa9f08fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade DB.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_salt', sa.CHAR(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade DB.
    """
    raise NotImplementedError("Downgrade is not supported")