"""fix default in firebase_uid in users

Revision ID: bafad400c9ed
Revises: fbbf5ef9c46a
Create Date: 2024-12-30 09:37:19.600420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafad400c9ed'
down_revision = 'fbbf5ef9c46a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade DB.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade DB.
    """
    raise NotImplementedError("Downgrade is not supported")