"""init users table

Revision ID: dd4432561444
Revises: 
Create Date: 2024-12-26 09:05:17.017316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4432561444'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade DB.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade DB.
    """
    raise NotImplementedError("Downgrade is not supported")