"""add the email to user

Revision ID: ec006a6056e4
Revises: 82c26f76d78a
Create Date: 2024-12-27 08:09:10.880313

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec006a6056e4'
down_revision = '82c26f76d78a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade DB.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade DB.
    """
    raise NotImplementedError("Downgrade is not supported")