"""fix problem with naming in users

Revision ID: fbbf5ef9c46a
Revises: ec006a6056e4
Create Date: 2024-12-30 09:36:17.811066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbf5ef9c46a'
down_revision = 'ec006a6056e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade DB.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.UUID(), nullable=True))
    op.drop_column('users', 'firebase_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade DB.
    """
    raise NotImplementedError("Downgrade is not supported")